
class DatabaseException(Exception):
    ...

class DatabaseDeleteException(Exception):
    ...

class DatabaseInsertionException(Exception):
    ...

class DatabaseUpdateException(Exception):
    ...